<td width="508" valign="top">
<p />
<p />
<p />
<p />
    <table width="500" border="0" align="center">
      <tbody><tr>
	  <td colspan="2">
        <?php //<div style="padding-left:5px;" class=normal> ?>
<h1>OpenStreetMap nedir?</h1><br><a href="http://www.openstreetmap.org" target="_blank">http://www.openstreetmap.org</a><p>OpenStreetMap açık kaynaklı olan ve dünyanın heryerinden gönüllü olarak katılımcıların oluşturdukları bir dünya haritası projesidir. OpenStreetMap tıpkı Vikipedi (ki Vikipedi'den esinlenmiştir) gibi kullanıcıların içeriklerini oluşturduğu bir yapıya sahiptir. Haritalar kullanıcıların sunmuş olduğu GPS izleri, uydu fotoğrafları ve yerel yönetimler tarafından sağlanan çeşitli veriler doğrultusunda oluşturulmaktadır. Yapılan değişiklikler &quot;anında&quot; yayınlanır.</p><p>OpenStreetMap'de bütün içerik &quot;Creative Commons Attribution-ShareAlike 2.0&quot; lisansı ile korunmaktadır.<br>Katkılar üreticilerine ait olmaya devam etmekle birlikte, &quot;copyleft&quot;lisansı içeriğin serbestçe dağıtımına olanak sağlamaktadır. Tamamen bedava ve tamamen reklamsızdır. Bir çok şirket ve yerel yönetim tarafından desteklenen bir projedir.</p><p>Dünya üzerinde pek çok ülkeden gönülüllerin katılımıyla büyümeye devam eden OpenStreetMap, bugün pek çok şehrin özgür haritasını barındırmaktadır. Google, Yahoo! gibi büyük sponsorların da yardımıyla cazip bir kullanım alanı oluşturan OpenStreetMap'e siz de katkı verebilirsiniz.</p><p>Katkı vermek için yapmanız gereken tek şey, bir GPS cihazına sahip olmanız veya OpenStreetMap'de kullanılmak üzere uydu fotoğrafları sağlamaktır.</p><p><strong>OpenStreetMap'in Genel Özellikleri</strong><br>*GPS izlerini aktarmak için özel yazılım gerektirmez. İnternet tarayıcınızın olması yeterlidir.<br>*Basit GPS verilerini kullanıcı doğrudan aktarabilir, büyük GPS verilerinde ise teknik ekip aktarımına yardımcı olur.<br>*Eklenen GPS verilerine katkı olarak sağlanan uydu görüntüleri ile dünya haritasının çıkarılması hızlandırılır.<br>*Ayrıca gönüllülerin bir araya gelerek belirli dönemlerde faaliyet olarak, haftasonları veya akşamları GPS verisi topladıkları bilinmektedir.<br>*İngiltere ve ABD gibi ülkelerde, "Özgür Veri Bankası" oluşturma fikirleri doğrultusunda kampanyalar düzenlenmektedir.<br>*Katılmak isteyip de nasıl katkıda bulunacağını bilmeyen kullanıcılar için <a href="http://wiki.openstreetmap.org">OpenStreetMap Wiki</a> sitesinde oldukça detaylı bir bilgi havuzu barındırmaktadır.<br>*Yararlanmak isteyenlere çeşitli çevrimiçi sitelerden, çevrimdışı olarak çeşitli uygulamalardan, mobil cihazlardan, bazı GPS alıcılarından, ağ günlüklerinden, Flickr vb. sitelerden ve harita verilerinden istedikleri veriye ulaşmalarını mümkün kılmaktadır.<br>Kullanım alanları ve daha kapsamlı bilgiye Vikipedi üzerinde bulunan <a href="http://en.wikipedia.org/wiki/OpenStreetMap">OpenStreetMap sayfasından</a> ulaşabilirsiniz.<br></p>
<?php//</div><br><br>
?>
</td>
    </tbody></table></td>