<td width="508" valign="top">
<p />
<p />
<p />
<p />
    <table width="500" border="0" align="center">
      <tbody><tr>
	  <td colspan="2">
        <?php //<div style="padding-left:5px;" class=normal> ?>
<h1>Wikipedia/Vikipedi nedir?</h1><br><a href="http://tr.wikipedia.org" target="_blank">http://tr.wikipedia.org</a><p>Vikipedi açık kaynaklı olan ve dünyanın heryerinden gönüllü olarak katılımcıların yazdıkları ile oluşturdukları Wikipedia ansiklopedisi projesinin Türkçe koludur. Vikipedi bir wiki sitesidir, yani herkes her sayfayı kayıt olmasına gerek bile olmadan oluşturabilir ve/veya değiştirebilir. Yapılan değişiklikler &quot;anında&quot; yayınlanır.<br>Tarafsızdır. Kuralları tüm kullanıcılar birlikte koyar.</p><p>Vikipedi'de bütün yazılar &quot;GNU Özgür Belgeleme Lisansı&quot; altındadır.<br>Katkılar üreticilerine ait olmaya devam etmekle birlikte, &quot;copyleft&quot;lisansı içeriğin serbestçe dağıtımına olanak sağlamaktadır. Tamamen bedava ve tamamen reklamsızdır. Google, Yahoo! gibi dünyanın önde gelen birçok şirketi tarafından desteklenmektedir.</p><p>İlk olarak İngilizce olarak 15 Ocak 2001'de başlayan wikipedia projesi şu andan 200 yakın değişik dilde toplam 2 milyona yakın makale içermektedir. Türkçesi teknik olarak 5 Aralık 2002 tarihinde başlamış olsa da, ilk makale eklemelerinin başlaması 2004 yılı başlarını bulmuştur. 1 Temmuz 2005 itibariyle 3649 Türkçe sayfanın üzerinde çalışılmaktadır. Bu sayı İngilizce Wikipedia'da 600 binin üzerindedir.</p><p>Şu anda Türkçe Vikipedi diğer dillerle karşılaştırıldığında çok yavaş ilerlemektedir. Bunun en büyük sebebi de çok az katılımcının olmasıdır. Her geçen gün katılımcılar artsa da, diğer dilleri yakalayabilmek için daha çok katılımcılara (size) ihtiyaç duymaktadır.</p><p><strong>Belli başlı özellikleri</strong><br>*Okumak ve değişiklik yapma için özel yazılım gerektirmez. İnternet tarayıcınızın olması yeterlidir.<br>*Çok basit olarak düz yazılar eklenebildiği gibi, resimlerle, tablolarla, grafiklerle özgün sayfa dizaynlarına olanak tanır.<br>*Diller arası bağlantı sağlayarak, okuduğunuz makaleyi diğer dillerde görme imkanı sunar.<br>*Sayfalar üzerinde yapılan tüm değişikliklerin kronolojisine ulaşma imkanı verir ve böylece kullanıcıya sayfanın nasıl bir değişimden geçtiğini görme fırsatı tanır.<br>*Sayfalar kategorilere eklenip konuyla ilgili diğer makalelere kolayca ulaşma imkanı verir.<br>*Şablon oluşturabilme özelliği ile birçok sayfada tekrarlanan içeriğin aynı şekile sahip olmasını sağlar.<br>*Her başlığın birde tatışma sayfası vardır. Böylece isteyenlere makale ile ilgili yorum yapma, soru sorma, konuyla ilgili sohbet etme imkanı verir. Bir topluluk ortamı yaratır.<br></p>
<?php//</div><br><br>
?>
</td>
    </tbody></table></td>