<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" <?php language_attributes(); ?>>
  <head profile="http://gmpg.org/xfn/11">
    <meta http-equiv="Content-Type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />
    <title><?php wp_title('&laquo;', true, 'right'); ?> <?php bloginfo('name'); ?></title>
    <link rel="stylesheet" href="<?php bloginfo('stylesheet_url'); ?>" type="text/css" media="screen" />
    <link rel="alternate" type="application/rss+xml" title="<?php bloginfo('name'); ?> RSS Feed" href="<?php bloginfo('rss2_url'); ?>" />
    <link rel="alternate" type="application/atom+xml" title="<?php bloginfo('name'); ?> Atom Feed" href="<?php bloginfo('atom_url'); ?>" />
    <link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
    <link rel="icon" type="image/png" href="<?php bloginfo('template_url'); ?>/images/favicon.png" />
    <script type="text/javascript" src="<?php bloginfo('template_url'); ?>/javascript/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="<?php bloginfo('template_url'); ?>/javascript/menu.js"></script>
    <script type="text/javascript" src="<?php bloginfo('template_url'); ?>/javascript/buttons.js"></script>

    <?php if ( is_singular() ) wp_enqueue_script( 'comment-reply' ); ?>
    <?php wp_head(); ?>

<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://istatistik.linux.org.tr/" : "http://istatistik.linux.org.tr/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 3);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://istatistik.linux.org.tr/piwik.php?idsite=3" style="border:0" alt="" /></p></noscript>
<!-- End Piwik Tracking Code -->
<!-- Generated by Revive Adserver 3.0.2 -->
<script type='text/javascript' src='http://reklam.lkd.org.tr/www/delivery/spcjs.php?id=1'></script>
  </head>
  <body>
    <div id="top">
      <div class="wrapper" id="header">
        <a href="<?php bloginfo('siteurl'); ?>">
          <img class="logo" src="<?php bloginfo('template_url'); ?>/images/logo.png" />
        </a>
        <script type='text/javascript'><!--// <![CDATA[
            /* [id1] 468x60 - linux.org.tr */
            OA_show(1);
        // ]]> --></script><noscript><a target='_blank' href='http://reklam.lkd.org.tr/www/delivery/ck.php?n=02002ad'><img border='0' alt='' src='http://reklam.lkd.org.tr/www/delivery/avw.php?zoneid=1&amp;n=02002ad' /></a></noscript>
      </div>
      <?php include 'menu.php'; ?>
    </div>
    <!-- Header part is finished -->
